spring.application.name=api

# =========================
# DATABASE - H2 DEV
# =========================
spring.datasource.url=jdbc:h2:mem:api;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =========================
# FLYWAY
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.validate-migration-naming=true

# =========================
# JPA / HIBERNATE
# =========================

# Hibernate não cria nem altera a estrutura.
# Apenas valida se as entidades batem com as migrations.
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# H2 CONSOLE
# =========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# JWT
# =========================
jwt.secret=3tjLplvVn6wmq5r7IJyOiNbCaluFfuAbv5W0OKvTxTM=
jwt.expiration=24h

# =========================
# API
# =========================
api.v1.prefix=/api/v1

# =========================
# FRONT
# =========================
front.base.url=http://localhost:3000