spring.application.name=api

# =========================
# DATABASE - POSTGRES PROD
# =========================
spring.datasource.url=jdbc:postgresql://simtese-db:5432/simtese-db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=matheusfragadevsimtese
spring.datasource.password=Simtese@2026

# =========================
# FLYWAY
# =========================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true
spring.flyway.validate-migration-naming=true

# =========================
# JPA / HIBERNATE
# =========================

# Hibernate não cria nem altera a estrutura.
# Apenas valida se as entidades batem com as migrations.
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# =========================
# H2 CONSOLE
# =========================
spring.h2.console.enabled=false

# =========================
# REDIS
# =========================
spring.data.redis.host=simtese-redis
spring.data.redis.port=6379
spring.data.redis.password=Simtese@2026

# =========================
# JWT
# =========================
jwt.secret=3tjLplvVn6wmq5r7IJyOiNbCaluFfuAbv5W0OKvTxTM=
jwt.expiration=30d

# =========================
# API
# =========================
api.v1.prefix=/api/v1

# =========================
# FRONT
# =========================
front.base.url=https://www.simtese.com.br/

# =========================
# FILE STORAGE
# =========================
results.path=/data/results

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=21MB
