services:
  postgres:
    image: postgres:16-alpine
    container_name: simtese-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: simtese-db
      POSTGRES_USER: matheusfragadevsimtese
      POSTGRES_PASSWORD: Simtese@2026
    volumes:
      - api-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matheusfragadevsimtese -d simtese-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: simtese-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "Simtese@2026"]
    volumes:
      - api-redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --no-auth-warning -a Simtese@2026 ping | grep -q PONG"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    image: eclipse-temurin:25-jre
    container_name: simtese-api
    restart: unless-stopped
    working_dir: /app
    environment:
      SPRING_PROFILES_ACTIVE: prod
    entrypoint: >
      sh -c "java -jar $(ls /jar/*.jar | grep -v -- '-plain.jar' | head -n1)"
    ports:
      - "8082:8080"
    volumes:
      - .:/jar:ro
      - api-logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  api-postgres-data:
  api-redis-data:
  api-logs:
